### ISSUE TITLE
static channel backup and recovery for local and remote nodes

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#127]
https://github.com/lightningnetwork/lnd/pull/2313

**Comment by xColliNx** [comment]
I think for remote nodes, the backup should be done by the node?

**Comment by ottosuess** [comment]
wouldn't it be cool to have a backup on the phone?

i'm too lazy to setup sophisticated backup solutions on my nodes by connecting them to dropbox or aws. the app on the phone could keep backups without any extra work required by the user.

**Comment by giulnz** [comment]
First , check this easy and clean solution for dropbox https://gist.github.com/vindard/e0cd3d41bb403a823f3b5002488e3f90 .
Second i know there is LND gRPC API SubscribeChannelBackups request to automatically get the newest channel backup file. https://api.lightning.community/#subscribechannelbackups 
Don't know if it can be helpful for your idea. It's can be nice that zap auto copy channels.backup to the iphone. But the problem is that it need to be automatic and also we need to do the restore part.

**Comment by knutnyg** [comment]
Love this! As the backup is encrypted - I say we minimum need only a way to get the backup out of the phone. Be that email, copy to documents/dropbox or something like that.
