### ISSUE TITLE
reset pin

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#140]
either by resetting the whole app or by entering the seed of a (local?) wallet.

**Comment by giulnz** [comment]
you mean you lost the pin and there is no way to reset the app ? you can add a reset button in pin screen that reset the pin but also the connection info, so if you reset the pin you must re-connect the node.

**Comment by ottosuess** [comment]
yes, but that sucks if you have lnd running on the phone (not possible now but will be soon).
i've seen other wallets that let you enter the seed to reset your pin. maybe we can have both.

**Comment by giulnz** [comment]
Ah ! understand the problem is mobile lnd.
if you reset you will lose open channel or at least with last static backup you can restore but we don’t have backup on zap and also it’s something not suggested to do. (Friction)
Anyway about reset, I was looking how to totally remove all zap data from iOS but that’s impossible or I don’t know how to do. If I delete the app when I reinstall it keep my lnd connect info. But what if I want a totally reset ? How to do it ?

**Comment by ottosuess** [comment]
right now it's not possible to do a total reset from the UI

**Comment by giulnz** [comment]
Ok, what if I need to do ? There is a technical way ? 
Actually I have 2 problem that I think can solve with a reset

**Comment by ottosuess** [comment]
pin can now be reset by deleting the app
