### ISSUE TITLE
Balance doesn't automatically update after receiving payment

### ISSUE THREAD

**Issue by Z-and** [LN-Zap/zap-iOS#266]
One thing I've noticed with all Zap releases is that your total balance doesn't update after receiving a payment (even when the payment shows up in the history tab). Seems like the only way to update is by reopening the app. Any plans on correcting this?

**Comment by JimmyMow** [comment]
Hmmm, good catch @Z-and. I was able to reproduce this actually. Certainly not the intended functionality, this seems like a bug. Certainly will look into correcting this

**Comment by chitowncrispy** [comment]
Is this the case for both on-chain and lightning payments? Or is it only the case for either on-chain or lightning payments?

**Comment by Z-and** [comment]
> Is this the case for both on-chain and lightning payments? Or is it only the case for either on-chain or lightning payments?

As far as I know it's only lightning. I haven't tested for on-chain payments

**Comment by JimmyMow** [comment]
My only run into this has been receiving Lightning payments as well

**Comment by chitowncrispy** [comment]
I have been testing this today and it seems like I have some steps to reproduce as well as get the total balance to refresh in the app.

While I am on testnet I can use the following [tool](http://lnd.fun/pay) to fulfill invoices that I create in order to send me payments over the lightning network. When the invoice is fulfilled the app will update the history view automatically with the payment received and will show the correct credited amount. The total balance, as well as the channels page with all the channels and the capacities for those channels, will not update automatically until a few payments have been processed. After a few payments have been processed it seems as though the total balance, as well as the channels page, will update automatically.

This may be an issue with the signals/observers we have for these given events and how they are bound to those respective UI pages/items.
