### ISSUE TITLE
my node view

### ISSUE THREAD

**Issue by ottosuess** [LN-Zap/zap-iOS#277]
We want to remove the tab bar and add a "my node" screen that contains details related to the connected node.

Here you can see the flow as it is right now:
![Screen Recording 2019-10-09 at 16 16 41 2019-10-09 16_22_25](https://user-images.githubusercontent.com/37940680/66490196-11304d80-eab1-11e9-87c2-e42186948287.gif)

still need a design for the node detail. 
what's still missing in the current version is the node alias and info about the network the node is connected to.

**Comment by ottosuess** [comment]
**sign and verify messages** could also live on this screen
more info:
https://twitter.com/JackMallers/status/1181963178604974082

**Comment by JimmyMow** [comment]
This is my CashApp profile page, I feel like this is the vibe we're going for

![image](https://user-images.githubusercontent.com/4040039/66588406-aa806200-eb8c-11e9-899e-ed3635d8cf2a.png)

- Top left QR code can be shown if the user is a remote node, and when it's clicked we can show the Node URI modal

- Instead of the camera icon asking the user to upload an image, we can just use a Zap logo

- Then all the other tabled options listed below

Thoughts? Maybe a good place to start?

**Comment by ottosuess** [comment]
yes. i like 🙌 @ole1220

**Comment by sohomang** [comment]
Here's a first proposal inspired by the Cash App, N26 and the iPhone settings. Really dig their _Profile_ on top of the screen, displaying useful info and status. I think we should restrict this screen to 3 to 5 top-level menu entries, which _could_ be described as there's a lot of free whitespace.

- The` IP address` label wouldn't be displayed on a local wallet.
- A click on the `Node details` button would open the current `Node URI modal`. Or the right side of the button could do this while the left side would directly copy the node's URI to clipboard?
- Haven't thought much about the copy, we can do much better

![My Node@3x](https://user-images.githubusercontent.com/28465517/66657988-dceb9700-ec40-11e9-8c6f-e4c36262721e.png)
